import { IProductItem } from "src/types/product";
import { Product } from "src/types/product-dto";

export function adaptProductDtoToItem(dto: Product): IProductItem {
  return {
    id: String(dto.id),
    sku: dto.sku ?? "",
    name: dto.name ?? "",
    code: dto.sku ?? String(dto.id),
    price: dto.sale_price ? Number(dto.sale_price) : Number(dto.price),
    taxes: 0,
    tags: dto.tags ?? [],
    gender: "",
    sizes: [],
    variants: dto.variants as any,
    publish: dto.status === "active" ? "published" : "draft",
    coverUrl: dto.images?.[0] ?? "",
    images: dto.images ?? [],
    isFeatured: dto.is_featured ?? false,
    productPrice: Number(dto.price),
    is_new: false,
    is_sale: Boolean(dto.sale_price),
    colors: [],
    quantity: dto.stock_quantity ?? 0,
    category: dto.category?.name ?? "",
    available: dto.stock_quantity ?? 0,
    totalSold: 0,
    description: dto.description ?? "",
    totalRatings: 0,
    totalReviews: 0,
    inventoryType: (dto.stock_quantity ?? 0) > 0 ? "In Stock" : "Out of Stock",
    subDescription: "",
    priceSale: dto.sale_price ? Number(dto.sale_price) : null,
    reviews: [],
    createdAt: dto.created_at ? new Date(dto.created_at) : new Date(),
    ratings: [],
    saleLabel: { enabled: Boolean(dto.sale_price), content: "Sale" },
    newLabel: { enabled: false, content: "New" },
    modelHeight: 0,
    modelSize: 0,
  };
}
