import { IProductItem } from "src/types/product";

export const SAMPLE_PRODUCTS: IProductItem[] = [
  {
    id: "p1",
    sku: "SKU-P1",
    name: "Goxx 02",
    modelHeight: 180,
    modelSize: 42,
    code: "GOXX-02",
    price: 580,
    taxes: 0,
    tags: ["new"],
    gender: "Men",
    sizes: ["XS", "S", "M", "L", "XL"],
    publish: "published",
    coverUrl: "/assets/images/home/products/product-1.avif",
    images: [
      "/assets/images/home/products/product-1.avif",
      "/assets/images/home/products/product-2.avif",
      "/assets/images/home/products/product-3.avif",
    ],
    colors: ["#1890FF", "#FF4842", "#00AB55", "#FFC107"],
    quantity: 10,
    category: "Shose",
    available: 10,
    totalSold: 120,
    description:
      "Comfortable everyday sneakers with breathable mesh upper and cushioned midsole for all-day wear.",
    totalRatings: 4.4,
    productPrice: 580,
    totalReviews: 12,
    inventoryType: "in_stock",
    subDescription: "Lightweight and durable. Perfect for casual outfits.",
    isFeatured: false,
    is_new: true,
    is_sale: false,
    priceSale: null,
    reviews: [],
    createdAt: new Date(),
    ratings: [
      { name: "1 Star", starCount: 1, reviewCount: 1 },
      { name: "2 Star", starCount: 2, reviewCount: 1 },
      { name: "3 Star", starCount: 3, reviewCount: 2 },
      { name: "4 Star", starCount: 4, reviewCount: 5 },
      { name: "5 Star", starCount: 5, reviewCount: 3 },
    ],
    saleLabel: { enabled: false, content: "" },
    newLabel: { enabled: true, content: "NEW" },
  },
  {
    id: "p2",
    sku: "SKU-P2",
    name: "Hypnosis A02",
    modelHeight: 175,
    modelSize: 40,
    code: "HYPN-A02",
    price: 560,
    taxes: 0,
    tags: ["sale"],
    gender: "Women",
    sizes: ["XS", "S", "M", "L"],
    publish: "published",
    coverUrl: "/assets/images/home/products/product-2.avif",
    images: [
      "/assets/images/home/products/product-2.avif",
      "/assets/images/home/products/product-1.avif",
    ],
    colors: ["#FF4842", "#FFC107", "#000000"],
    quantity: 5,
    category: "Apparel",
    available: 5,
    totalSold: 90,
    description: "Stylish and modern silhouette with premium materials.",
    totalRatings: 4.8,
    productPrice: 500,
    totalReviews: 20,
    inventoryType: "sale",
    subDescription: "Best seller with limited time discount.",
    isFeatured: false,
    is_new: false,
    is_sale: true,
    priceSale: 560,
    reviews: [],
    createdAt: new Date(),
    ratings: [
      { name: "1 Star", starCount: 1, reviewCount: 0 },
      { name: "2 Star", starCount: 2, reviewCount: 1 },
      { name: "3 Star", starCount: 3, reviewCount: 2 },
      { name: "4 Star", starCount: 4, reviewCount: 6 },
      { name: "5 Star", starCount: 5, reviewCount: 11 },
    ],
    saleLabel: { enabled: true, content: "SALE" },
    newLabel: { enabled: false, content: "" },
  },
  {
    id: "p3",
    sku: "SKU-P3",
    name: "Paranoyd 02",
    modelHeight: 168,
    modelSize: 38,
    code: "PARA-02",
    price: 450,
    taxes: 0,
    tags: [],
    gender: "Kids",
    sizes: ["XS", "S"],
    publish: "published",
    coverUrl: "/assets/images/home/products/product-3.avif",
    images: ["/assets/images/home/products/product-3.avif"],
    colors: ["#00AB55", "#1890FF"],
    quantity: 0,
    category: "Accessories",
    available: 0,
    totalSold: 30,
    description: "Playful accessories with vibrant colors.",
    totalRatings: 3.5,
    productPrice: 450,
    totalReviews: 5,
    inventoryType: "out_of_stock",
    subDescription: "Limited stock. Check back soon!",
    isFeatured: false,
    is_new: false,
    is_sale: false,
    priceSale: null,
    reviews: [],
    createdAt: new Date(),
    ratings: [
      { name: "1 Star", starCount: 1, reviewCount: 1 },
      { name: "2 Star", starCount: 2, reviewCount: 1 },
      { name: "3 Star", starCount: 3, reviewCount: 1 },
      { name: "4 Star", starCount: 4, reviewCount: 1 },
      { name: "5 Star", starCount: 5, reviewCount: 1 },
    ],
    saleLabel: { enabled: false, content: "" },
    newLabel: { enabled: false, content: "" },
  },
];
