import { IProductItem } from "src/types/product";

export const SAMPLE_PRODUCTS: IProductItem[] = [
  {
    id: "p1",
    sku: "SKU-P1",
    variants: [],
    name: "Goxx 02",
    modelHeight: 180,
    modelSize: 42,
    code: "GOXX-02",
    price: 580,
    taxes: 0,
    tags: ["new"],
    gender: "Men",
    sizes: ["XS", "S", "M", "L", "XL"],
    publish: "published",
    coverUrl: "/assets/images/home/products/product-1.avif",
    images: [
      "/assets/images/home/products/product-1.avif",
      "/assets/images/home/products/product-2.avif",
      "/assets/images/home/products/product-3.avif",
    ],
    colors: ["#1890FF", "#FF4842", "#00AB55", "#FFC107"],
    quantity: 10,
    category: "Shose",
    available: 10,
    totalSold: 120,
    description:
      "Comfortable everyday sneakers with breathable mesh upper and cushioned midsole for all-day wear.",
    totalRatings: 4.4,
    productPrice: 580,
    totalReviews: 12,
    inventoryType: "in_stock",
    subDescription: "Lightweight and durable. Perfect for casual outfits.",
    isFeatured: false,
    is_new: true,
    is_sale: false,
    priceSale: null,
    reviews: [],
    createdAt: new Date(),
    ratings: [
      { name: "1 Star", starCount: 1, reviewCount: 1 },
      { name: "2 Star", starCount: 2, reviewCount: 1 },
      { name: "3 Star", starCount: 3, reviewCount: 2 },
      { name: "4 Star", starCount: 4, reviewCount: 5 },
      { name: "5 Star", starCount: 5, reviewCount: 3 },
    ],
    saleLabel: { enabled: false, content: "" },
    newLabel: { enabled: true, content: "NEW" },
  }
];
